#!/bin/bash
set -e

IMAGE="gliderlabs/herokuish"

COMMAND=$(cat <<EOF
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y software-properties-common python-software-properties
add-apt-repository ppa:jonathonf/ffmpeg-3
apt-get update
apt-get install -y ffmpeg
EOF
)

ID=$(docker run -d $IMAGE /bin/sh -c "$COMMAND")
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
